language: go
go:
- 1.5.1
- tip
env: PATH=/home/travis/gopath/bin:$PATH
install:
- go get ./...
- go get github.com/laher/goxc
script:
- go test -v
- goxc -d . -n yal
deploy:
  provider: releases
  api_key:
    secure: knLHB9K9y6mebhzzSUEx4NAPTIY9/rUozwq8YjGeyjDwKLBE8SluLVydXFAlXzUL74OflBnAFxaqyLb/cfkwVAJKpPmAh+nbR/pK+rjZyEtYvDnxvsT44YMU7Jc/BAqbAXEHEJFt5iDhLrvjLFu6WVkN8OEAsFvOnZ3A3f0vMZrlTAZSGqocBjXmc05H/XkGldw22jqCAx469+a7uKw0FbMuUzMsBxBrBGLkQe3pmVZsoouQjVngD49G57mIm4Z5j1vlNElltjL1IHa2ROm7frxlSy4qr8KuczTwS17I8uWG0QO1kSj3BJ7+YOSD2VbUS6Htf+U33t1IvA5Qo3HKWRCrzP5yosIoyhXKFw9V94bE1iLsQ85xah0mwkCj/IiMuCHzfybRoBWH0JMNh0eRzfv2ARPbLpIjTHHHVTB1RlIKpUsMmvFE9zi6BMwsCLGTvwgE9JezFV7uUQo4FBSLNk7q7P5yXMVtLkw6WXniItgazRaN+FYfI15L/QP0/6OIZvamzpb7nt/XDMIgj8qJk3bVxyjMrz6Px/7/lgzioxSyLzPa0qCWv5OCvsIvYbmIHn6Oxy2j4IhmIUdBHvy6jErYwDfq/LR/LLlRmo/P4oYmIYVYjovMee+CHGmr9HR9xjT5nYaV6ZZjBqMMdxH019T6WJxXgiX39YuGC3r2jyI=
  file:
    - snapshot/yal_linux_386.tar.gz
    - snapshot/yal_linux_arm.tar.gz
    - snapshot/yal_linux_amd64.tar.gz
    - snapshot/yal_windows_386.zip
    - snapshot/yal_windows_amd64.zip
    - snapshot/yal_darwin_amd64.zip
    - snapshot/yal_darwin_386.zip
  on:
    repo: mizkei/yalzo
    tags: true
    condition: "$TRAVIS_GO_VERSION = go1.5.1"
notifications:
  slack:
    secure: mtAspyDNUeGDr3LG1weHdwHJsgpQFOz6ngYCJuBsvMs+M1SCxH7tABwzUZCtXieoYFeZbEzW2UWNYBfWYEIu2SLIi4hGSj0XshtTw/vHlLCf3RWAPSXHtjXkcBRkHWrbofNZOq7Ake1GTfOhwhwI0t0uk6EVu2ova3RUraT5qjTBM/xuN2FNi2dB0HjtM79625+DOBeJT0HFFeFc5k+ohA+/hE+VnhMigHu5q8pjRTzvBqnvtU/bBXHvWPOA6T52z5/Y7rZz0OcedxtA0SCjEJsxnRZixDf0KpJsHJ32Kr8wsqH4z1h6CW6tTJxiekBZnQ+q2JYKdSiFglnpWQo5tyKApLAtXsJtJrTn+8G4+Kc7wC13cv/6TorZwAGEuEYXA3anV99EecJwX6S0G2TAcsXdEtPp8Myxu07CnPXPFlS/rwvFAAcua6eTYN26pSjDisZn/R4IXivfaG7ClFAVU1ui3jxFayzhzjaGG9lZFbs0jL+ahGQinu3rOvqXTjH7unS+Gud8bj4BpkMje7wcSMm3fQVTL5jSKwEYOcWRo9WiLv8Q2bVMW/rCctjZR4bVOsxZPWbIgNInIx5l82GgrFRv89I1pzkP9PbDCM6ce/dAetYfr9F7lsW8KhttSzRze5y+Bcud600BBH4J+jkTBuzKaXY6NA0wEtWvb75ti7A=
